"""
Merge existing nba_questions.json (ids 1-20) with 80 new seed items (ids 21-100).
Validates every SQL against data/raw/nba.sqlite before writing.
"""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DB = ROOT / "data/raw/nba.sqlite"
OUT = ROOT / "data/nba/nba_questions.json"
# Keep only canonical ids 1-20 so re-running this script replaces 21-100.
EXISTING = [x for x in json.loads(OUT.read_text(encoding="utf-8")) if x["id"] <= 20]

# (id, difficulty, question, query, tables_used, sql_components)
NEW: list[tuple] = [
    # --- easy 21-34 ---
    (
        21,
        "easy",
        "How many NBA teams are based in Texas?",
        "SELECT COUNT(*) FROM team WHERE state = 'Texas';",
        ["team"],
        ["count", "where"],
    ),
    (
        22,
        "easy",
        "List the full names of all teams based in Texas.",
        "SELECT full_name FROM team WHERE state = 'Texas' ORDER BY full_name;",
        ["team"],
        ["where", "order_by"],
    ),
    (
        23,
        "easy",
        "What is the abbreviation for the Miami Heat?",
        "SELECT abbreviation FROM team WHERE full_name = 'Miami Heat';",
        ["team"],
        ["where"],
    ),
    (
        24,
        "easy",
        "How many teams were founded in the year 1968?",
        "SELECT COUNT(*) FROM team WHERE year_founded = 1968;",
        ["team"],
        ["count", "where"],
    ),
    (
        25,
        "easy",
        "List the cities of teams whose nickname is 'Bulls'.",
        "SELECT city FROM team WHERE nickname = 'Bulls';",
        ["team"],
        ["where"],
    ),
    (
        26,
        "easy",
        "How many players in the player table are marked inactive?",
        "SELECT COUNT(*) FROM player WHERE is_active = 0;",
        ["player"],
        ["count", "where"],
    ),
    (
        27,
        "easy",
        "What is Stephen Curry's full name as stored in the player table?",
        "SELECT full_name FROM player WHERE first_name = 'Stephen' AND last_name = 'Curry';",
        ["player"],
        ["where"],
    ),
    (
        28,
        "easy",
        "How many draft history rows are there for the 1996 draft class?",
        "SELECT COUNT(*) FROM draft_history WHERE season = '1996';",
        ["draft_history"],
        ["count", "where"],
    ),
    (
        29,
        "easy",
        "How many regular season games were played in the 2021-22 season (season_id 22021)?",
        "SELECT COUNT(*) FROM game WHERE season_id = '22021' AND season_type = 'Regular Season';",
        ["game"],
        ["count", "where"],
    ),
    (
        30,
        "easy",
        "How many playoff games are recorded for season_id 22022?",
        "SELECT COUNT(*) FROM game WHERE season_id = '22022' AND season_type = 'Playoffs';",
        ["game"],
        ["count", "where"],
    ),
    (
        31,
        "easy",
        "List distinct season_type values that appear in the game table.",
        "SELECT DISTINCT season_type FROM game ORDER BY season_type;",
        ["game"],
        ["distinct", "order_by"],
    ),
    (
        32,
        "easy",
        "How many players in common_player_info are listed with roster status Active?",
        "SELECT COUNT(*) FROM common_player_info WHERE rosterstatus = 'Active';",
        ["common_player_info"],
        ["count", "where"],
    ),
    (
        33,
        "easy",
        "What arena does team_details list for the Los Angeles Lakers (abbreviation LAL)?",
        "SELECT arena FROM team_details WHERE abbreviation = 'LAL';",
        ["team_details"],
        ["where"],
    ),
    (
        34,
        "easy",
        "Who is listed as head coach for Boston (abbreviation BOS) in team_details?",
        "SELECT headcoach FROM team_details WHERE abbreviation = 'BOS';",
        ["team_details"],
        ["where"],
    ),
    # --- medium 35-54 ---
    (
        35,
        "medium",
        "In the 2022-23 regular season, how many home games did the Boston Celtics play?",
        "SELECT COUNT(*) FROM game WHERE team_name_home = 'Boston Celtics' AND season_id = '22022' AND season_type = 'Regular Season';",
        ["game"],
        ["count", "where"],
    ),
    (
        36,
        "medium",
        "What was the average home points per game for the Milwaukee Bucks at home in the 2022-23 regular season?",
        "SELECT AVG(pts_home) FROM game WHERE team_name_home = 'Milwaukee Bucks' AND season_id = '22022' AND season_type = 'Regular Season';",
        ["game"],
        ["aggregate", "where"],
    ),
    (
        37,
        "medium",
        "Which team had the most total home losses in the 2022-23 regular season?",
        "SELECT team_name_home, COUNT(*) AS losses FROM game WHERE wl_home = 'L' AND season_id = '22022' AND season_type = 'Regular Season' GROUP BY team_name_home ORDER BY losses DESC LIMIT 1;",
        ["game"],
        ["count", "group_by", "order_by", "limit"],
    ),
    (
        38,
        "medium",
        "How many games in the 2022-23 regular season ended with the home team scoring at least 130 points?",
        "SELECT COUNT(*) FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND pts_home >= 130;",
        ["game"],
        ["count", "where"],
    ),
    (
        39,
        "medium",
        "List the top 3 teams by average assists at home in the 2022-23 regular season.",
        "SELECT team_name_home, AVG(ast_home) AS avg_ast FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' GROUP BY team_name_home ORDER BY avg_ast DESC LIMIT 3;",
        ["game"],
        ["aggregate", "group_by", "order_by", "limit"],
    ),
    (
        40,
        "medium",
        "How many draft picks in draft_history were made by teams whose abbreviation is LAL?",
        "SELECT COUNT(*) FROM draft_history WHERE team_abbreviation = 'LAL';",
        ["draft_history"],
        ["count", "where"],
    ),
    (
        41,
        "medium",
        "How many first-round picks (round_number = '1') appear in the 2019 draft in draft_history?",
        "SELECT COUNT(*) FROM draft_history WHERE season = '2019' AND round_number = '1';",
        ["draft_history"],
        ["count", "where"],
    ),
    (
        42,
        "medium",
        "How many common_player_info rows list France as the country?",
        "SELECT COUNT(*) FROM common_player_info WHERE country = 'France';",
        ["common_player_info"],
        ["count", "where"],
    ),
    (
        43,
        "medium",
        "What is the average weight in draft_combine_stats for the 2022 combine class?",
        "SELECT AVG(weight) FROM draft_combine_stats WHERE season = '2022';",
        ["draft_combine_stats"],
        ["aggregate", "where"],
    ),
    (
        44,
        "medium",
        "How many distinct players appear in inactive_players for game_id starting with '00222' (2022-23 season games)?",
        "SELECT COUNT(DISTINCT player_id) FROM inactive_players WHERE game_id LIKE '00222%';",
        ["inactive_players"],
        ["count", "distinct", "where"],
    ),
    (
        45,
        "medium",
        "In the 2021-22 regular season, what was the average total points scored in a game (home + away)?",
        "SELECT AVG(pts_home + pts_away) FROM game WHERE season_id = '22021' AND season_type = 'Regular Season' AND pts_home IS NOT NULL AND pts_away IS NOT NULL;",
        ["game"],
        ["aggregate", "where"],
    ),
    (
        46,
        "medium",
        "How many regular season games in 2022-23 were decided by overtime (non-empty ot period minutes)?",
        "SELECT COUNT(*) FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND min > 240;",
        ["game"],
        ["count", "where"],
    ),
    (
        47,
        "medium",
        "List team_name_home and count of games where the home team made at least 20 three-pointers in the 2022-23 regular season, top 5 by count.",
        "SELECT team_name_home, COUNT(*) AS games FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND fg3m_home >= 20 GROUP BY team_name_home ORDER BY games DESC LIMIT 5;",
        ["game"],
        ["count", "group_by", "order_by", "limit"],
    ),
    (
        48,
        "medium",
        "What is the maximum single-game home team rebound total in the 2022-23 regular season?",
        "SELECT MAX(reb_home) FROM game WHERE season_id = '22022' AND season_type = 'Regular Season';",
        ["game"],
        ["aggregate", "where"],
    ),
    (
        49,
        "medium",
        "How many teams in team_details have a listed arena capacity of at least 20000?",
        "SELECT COUNT(*) FROM team_details WHERE arenacapacity IS NOT NULL AND CAST(arenacapacity AS INTEGER) >= 20000;",
        ["team_details"],
        ["count", "where"],
    ),
    (
        50,
        "medium",
        "In game_summary, how many games are recorded for NBA season year 2022?",
        "SELECT COUNT(*) FROM game_summary WHERE season = '2022';",
        ["game_summary"],
        ["count", "where"],
    ),
    (
        51,
        "medium",
        "How many officials rows list jersey_num 48?",
        "SELECT COUNT(*) FROM officials WHERE jersey_num = '48';",
        ["officials"],
        ["count", "where"],
    ),
    (
        52,
        "medium",
        "What is Kevin Durant's jersey number in common_player_info (display name match)?",
        "SELECT jersey FROM common_player_info WHERE display_first_last = 'Kevin Durant';",
        ["common_player_info"],
        ["where"],
    ),
    (
        53,
        "medium",
        "How many draft_history entries have overall_pick between 1 and 10 inclusive for season 2003?",
        "SELECT COUNT(*) FROM draft_history WHERE season = '2003' AND CAST(overall_pick AS INTEGER) BETWEEN 1 AND 10;",
        ["draft_history"],
        ["count", "where"],
    ),
    (
        54,
        "medium",
        "In the 2022-23 regular season, how many times did the home team score exactly 120 points?",
        "SELECT COUNT(*) FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND pts_home = 120;",
        ["game"],
        ["count", "where"],
    ),
    # --- hard 55-74 ---
    (
        55,
        "hard",
        "Which two teams played in the game with the highest combined points in the 2022-23 regular season?",
        "SELECT team_name_home, team_name_away, pts_home + pts_away AS total_pts FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' ORDER BY total_pts DESC LIMIT 1;",
        ["game"],
        ["order_by", "limit", "where"],
    ),
    (
        56,
        "hard",
        "Find players in common_player_info who are Active and listed at Guard position.",
        "SELECT display_first_last FROM common_player_info WHERE rosterstatus = 'Active' AND position LIKE '%Guard%' ORDER BY display_first_last LIMIT 15;",
        ["common_player_info"],
        ["where", "order_by", "limit"],
    ),
    (
        57,
        "hard",
        "For the 2022-23 regular season, which team had the lowest average home points allowed (pts_away) when playing at home?",
        "SELECT team_name_home, AVG(pts_away) AS opp_ppg FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' GROUP BY team_name_home ORDER BY opp_ppg ASC LIMIT 1;",
        ["game"],
        ["aggregate", "group_by", "order_by", "limit"],
    ),
    (
        58,
        "hard",
        "List draft_history player_name and team_name for all top-3 overall picks in the 2018 draft.",
        "SELECT player_name, team_name FROM draft_history WHERE season = '2018' AND CAST(overall_pick AS INTEGER) <= 3 ORDER BY CAST(overall_pick AS INTEGER);",
        ["draft_history"],
        ["where", "order_by"],
    ),
    (
        59,
        "hard",
        "How many games did Nikola Jokic appear on the inactive list (match first_name and last_name)?",
        "SELECT COUNT(*) FROM inactive_players WHERE first_name = 'Nikola' AND last_name = 'Jokic';",
        ["inactive_players"],
        ["count", "where"],
    ),
    (
        60,
        "hard",
        "Join game to line_score on game_id: how many 2022-23 regular season games have line_score data?",
        "SELECT COUNT(*) FROM game g JOIN line_score ls ON g.game_id = ls.game_id WHERE g.season_id = '22022' AND g.season_type = 'Regular Season';",
        ["game", "line_score"],
        ["join", "count", "where"],
    ),
    (
        61,
        "hard",
        "Which team_name_home averaged the highest free throw percentage at home in the 2022-23 regular season (minimum 41 home games)?",
        "SELECT team_name_home, AVG(ft_pct_home) AS avg_ft FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND ft_pct_home IS NOT NULL GROUP BY team_name_home HAVING COUNT(*) >= 41 ORDER BY avg_ft DESC LIMIT 1;",
        ["game"],
        ["aggregate", "group_by", "having", "order_by", "limit"],
    ),
    (
        62,
        "hard",
        "Count distinct game_id where both teams scored at least 120 points in the 2022-23 regular season.",
        "SELECT COUNT(*) FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND pts_home >= 120 AND pts_away >= 120;",
        ["game"],
        ["count", "where"],
    ),
    (
        63,
        "hard",
        "From draft_history, which college organization produced the most players drafted in 2015?",
        "SELECT organization, COUNT(*) AS cnt FROM draft_history WHERE season = '2015' AND organization_type = 'College/University' GROUP BY organization ORDER BY cnt DESC LIMIT 1;",
        ["draft_history"],
        ["aggregate", "group_by", "order_by", "limit"],
    ),
    (
        64,
        "hard",
        "List display_first_last from common_player_info for players on the Phoenix Suns (team_name) who are Active.",
        "SELECT display_first_last FROM common_player_info WHERE team_name = 'Suns' AND rosterstatus = 'Active' ORDER BY display_first_last LIMIT 20;",
        ["common_player_info"],
        ["where", "order_by", "limit"],
    ),
    (
        65,
        "hard",
        "In the 2021-22 regular season, how many home games did the Golden State Warriors win?",
        "SELECT COUNT(*) FROM game WHERE team_name_home = 'Golden State Warriors' AND season_id = '22021' AND season_type = 'Regular Season' AND wl_home = 'W';",
        ["game"],
        ["count", "where"],
    ),
    (
        66,
        "hard",
        "What is the median-like middle value: average of the 5th and 6th highest pts_home in 2022-23 RS for the Nuggets at home? (Use a subquery with LIMIT.)",
        "SELECT AVG(pts_home) FROM (SELECT pts_home FROM game WHERE team_name_home = 'Denver Nuggets' AND season_id = '22022' AND season_type = 'Regular Season' ORDER BY pts_home DESC LIMIT 2 OFFSET 4);",
        ["game"],
        ["subquery", "aggregate", "order_by", "limit"],
    ),
    (
        67,
        "hard",
        "Find teams that lost at home by 30 or more points at least once in the 2022-23 regular season (home score minus away score <= -30).",
        "SELECT DISTINCT team_name_home FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND pts_home - pts_away <= -30 ORDER BY team_name_home LIMIT 10;",
        ["game"],
        ["distinct", "where", "order_by", "limit"],
    ),
    (
        68,
        "hard",
        "How many players in draft_combine_stats from season 2021 have wingspan greater than 220 cm?",
        "SELECT COUNT(*) FROM draft_combine_stats WHERE season = '2021' AND wingspan > 220;",
        ["draft_combine_stats"],
        ["count", "where"],
    ),
    (
        69,
        "hard",
        "Which away team won the most road games in the 2022-23 regular season?",
        "SELECT team_name_away, COUNT(*) AS road_wins FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND wl_away = 'W' GROUP BY team_name_away ORDER BY road_wins DESC LIMIT 1;",
        ["game"],
        ["count", "group_by", "order_by", "limit"],
    ),
    (
        70,
        "hard",
        "Join common_player_info to draft_history on person_id: how many distinct players drafted in 2014 appear in both tables?",
        "SELECT COUNT(DISTINCT c.person_id) FROM common_player_info c JOIN draft_history d ON c.person_id = CAST(d.person_id AS TEXT) WHERE d.season = '2014';",
        ["common_player_info", "draft_history"],
        ["join", "count", "distinct", "where"],
    ),
    (
        71,
        "hard",
        "In the 2020-21 regular season (season_id 22020), which home team had the worst home record by win percentage?",
        "SELECT team_name_home, SUM(CASE WHEN wl_home = 'W' THEN 1 ELSE 0 END) * 1.0 / COUNT(*) AS win_pct FROM game WHERE season_id = '22020' AND season_type = 'Regular Season' GROUP BY team_name_home ORDER BY win_pct ASC LIMIT 1;",
        ["game"],
        ["aggregate", "group_by", "order_by", "limit"],
    ),
    (
        72,
        "hard",
        "List game_id and pts_home for Denver Nuggets home games in 2022-23 RS where they scored at least 140 points, ordered by pts_home descending.",
        "SELECT game_id, pts_home FROM game WHERE team_name_home = 'Denver Nuggets' AND season_id = '22022' AND season_type = 'Regular Season' AND pts_home >= 140 ORDER BY pts_home DESC;",
        ["game"],
        ["where", "order_by"],
    ),
    (
        73,
        "hard",
        "How many draft_history rows have team_city 'Philadelphia' and season between 2010 and 2015 inclusive?",
        "SELECT COUNT(*) FROM draft_history WHERE team_city = 'Philadelphia' AND CAST(season AS INTEGER) BETWEEN 2010 AND 2015;",
        ["draft_history"],
        ["count", "where"],
    ),
    (
        74,
        "hard",
        "Which position appears most often among Active players in common_player_info?",
        "SELECT position, COUNT(*) AS cnt FROM common_player_info WHERE rosterstatus = 'Active' GROUP BY position ORDER BY cnt DESC LIMIT 1;",
        ["common_player_info"],
        ["aggregate", "group_by", "order_by", "limit"],
    ),
    # --- extra_hard 75-100 ---
    (
        75,
        "extra_hard",
        "Compare 2022-23 vs 2021-22: which team improved its average home scoring margin (pts_home - pts_away) the most?",
        "SELECT a.team_name_home, (a.avg_m - b.avg_m) AS improvement FROM (SELECT team_name_home, AVG(pts_home - pts_away) AS avg_m FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' GROUP BY team_name_home) a JOIN (SELECT team_name_home, AVG(pts_home - pts_away) AS avg_m FROM game WHERE season_id = '22021' AND season_type = 'Regular Season' GROUP BY team_name_home) b ON a.team_name_home = b.team_name_home ORDER BY improvement DESC LIMIT 1;",
        ["game"],
        ["subquery", "join", "aggregate", "order_by", "limit"],
    ),
    (
        76,
        "extra_hard",
        "Among players drafted first overall (overall_pick = '1') in draft_history, list those who are still Active in common_player_info (join on person_id).",
        "SELECT DISTINCT c.display_first_last, d.season FROM draft_history d JOIN common_player_info c ON c.person_id = CAST(d.person_id AS TEXT) WHERE d.overall_pick = '1' AND c.rosterstatus = 'Active' ORDER BY d.season DESC LIMIT 15;",
        ["draft_history", "common_player_info"],
        ["join", "distinct", "where", "order_by", "limit"],
    ),
    (
        77,
        "extra_hard",
        "For each season_id in ('22020','22021','22022'), compute league average pts_home per regular season game; return three rows.",
        "SELECT season_id, AVG(pts_home) AS league_avg_home_pts FROM game WHERE season_id IN ('22020', '22021', '22022') AND season_type = 'Regular Season' GROUP BY season_id ORDER BY season_id;",
        ["game"],
        ["aggregate", "group_by", "where", "order_by"],
    ),
    (
        78,
        "extra_hard",
        "Find game_id where the home team had at least 55 rebounds (reb_home) in a 2022-23 regular season game.",
        "SELECT game_id, team_name_home, reb_home FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND reb_home >= 55 ORDER BY reb_home DESC LIMIT 10;",
        ["game"],
        ["where", "order_by"],
    ),
    (
        79,
        "extra_hard",
        "Using a window average, list teams whose home-point variance (population variance of pts_home) in 2022-23 RS exceeds 4.",
        "SELECT team_name_home FROM (SELECT team_name_home, AVG((pts_home - avg_ph) * (pts_home - avg_ph)) AS var_sum, COUNT(*) AS n FROM (SELECT team_name_home, pts_home, AVG(pts_home) OVER (PARTITION BY team_name_home) AS avg_ph FROM game WHERE season_id = '22022' AND season_type = 'Regular Season') x GROUP BY team_name_home) y WHERE (var_sum / n) > 4 ORDER BY var_sum / n DESC LIMIT 5;",
        ["game"],
        ["window", "subquery", "aggregate"],
    ),
    (
        80,
        "extra_hard",
        "Simpler variance question: Which team had the largest range (max pts_home - min pts_home) at home in 2022-23 regular season?",
        "SELECT team_name_home, MAX(pts_home) - MIN(pts_home) AS spread FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' GROUP BY team_name_home ORDER BY spread DESC LIMIT 1;",
        ["game"],
        ["aggregate", "group_by", "order_by", "limit"],
    ),
    (
        81,
        "extra_hard",
        "Double join: games where Jayson Tatum was inactive — count distinct game_id.",
        "SELECT COUNT(DISTINCT i.game_id) FROM inactive_players i WHERE i.first_name = 'Jayson' AND i.last_name = 'Tatum';",
        ["inactive_players"],
        ["count", "distinct", "where"],
    ),
    (
        82,
        "extra_hard",
        "For 2022-23 regular season, list matchup_home patterns containing 'vs.' for the Lakers at home, limit 5 distinct patterns.",
        "SELECT DISTINCT matchup_home FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND team_name_home = 'Los Angeles Lakers' AND matchup_home LIKE '%vs.%' LIMIT 5;",
        ["game"],
        ["distinct", "where", "limit"],
    ),
    (
        83,
        "extra_hard",
        "Players drafted in round 2 after pick 50 in 2016: count rows in draft_history.",
        "SELECT COUNT(*) FROM draft_history WHERE season = '2016' AND round_number = '2' AND CAST(overall_pick AS INTEGER) > 50;",
        ["draft_history"],
        ["count", "where"],
    ),
    (
        84,
        "extra_hard",
        "CTE-style via subquery: top 10 players by games inactive in 2022-23 season games (game_id prefix 00222).",
        "SELECT first_name, last_name, COUNT(*) AS cnt FROM inactive_players WHERE game_id LIKE '00222%' GROUP BY first_name, last_name ORDER BY cnt DESC LIMIT 10;",
        ["inactive_players"],
        ["aggregate", "group_by", "order_by", "limit"],
    ),
    (
        85,
        "extra_hard",
        "Home court advantage index: for 2022-23 RS, difference between home win rate and overall win rate approximation — show team with biggest (home_wins/home_games - wins/total_games). Use only home slice for simplicity: teams with highest home win rate.",
        "SELECT team_name_home, SUM(CASE WHEN wl_home = 'W' THEN 1 ELSE 0 END) * 1.0 / COUNT(*) AS home_win_rate FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' GROUP BY team_name_home ORDER BY home_win_rate DESC LIMIT 3;",
        ["game"],
        ["aggregate", "group_by", "order_by", "limit"],
    ),
    (
        86,
        "extra_hard",
        "Which official (first_name, last_name) appears most often in the officials table?",
        "SELECT first_name, last_name, COUNT(*) AS appearances FROM officials GROUP BY first_name, last_name ORDER BY appearances DESC LIMIT 1;",
        ["officials"],
        ["aggregate", "group_by", "order_by", "limit"],
    ),
    (
        87,
        "extra_hard",
        "game_info: count rows with attendance above 19000 for season 22022 games — join game on game_id.",
        "SELECT COUNT(*) FROM game g JOIN game_info gi ON g.game_id = gi.game_id WHERE g.season_id = '22022' AND g.season_type = 'Regular Season' AND gi.attendance IS NOT NULL AND CAST(gi.attendance AS INTEGER) > 19000;",
        ["game", "game_info"],
        ["join", "count", "where"],
    ),
    (
        88,
        "extra_hard",
        "other_stats: average home team_turnovers_home for 2022-23 regular season games (join game).",
        "SELECT AVG(CAST(o.team_turnovers_home AS REAL)) FROM game g JOIN other_stats o ON g.game_id = o.game_id WHERE g.season_id = '22022' AND g.season_type = 'Regular Season';",
        ["game", "other_stats"],
        ["join", "aggregate", "where"],
    ),
    (
        89,
        "extra_hard",
        "play_by_play is huge — count how many scoring events (eventmsgtype = 1) occurred in game_id = (SELECT game_id FROM game WHERE season_id='22022' AND season_type='Regular Season' ORDER BY pts_home+pts_away DESC LIMIT 1).",
        "SELECT COUNT(*) FROM play_by_play WHERE game_id = (SELECT game_id FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' ORDER BY pts_home + pts_away DESC LIMIT 1) AND eventmsgtype = 1;",
        ["play_by_play", "game"],
        ["subquery", "count", "where"],
    ),
    (
        90,
        "extra_hard",
        "team_history: how many franchise name changes are recorded?",
        "SELECT COUNT(*) FROM team_history;",
        ["team_history"],
        ["count"],
    ),
    (
        91,
        "extra_hard",
        "Which combine seasons in draft_combine_stats have fewer than 50 participants (HAVING)?",
        "SELECT season FROM draft_combine_stats GROUP BY season HAVING COUNT(*) < 50 ORDER BY season DESC LIMIT 10;",
        ["draft_combine_stats"],
        ["aggregate", "group_by", "having", "order_by", "limit"],
    ),
    (
        92,
        "extra_hard",
        "game_summary join game on game_id: count games in 2022 calendar season field where home_team_id corresponds to Chicago Bulls team id from team table.",
        "SELECT COUNT(*) FROM game_summary gs JOIN team t ON gs.home_team_id = t.id JOIN game g ON gs.game_id = g.game_id WHERE gs.season = '2022' AND t.full_name = 'Chicago Bulls';",
        ["game_summary", "team", "game"],
        ["join", "count", "where"],
    ),
    (
        93,
        "extra_hard",
        "Union: combine home and away team names from 2022-23 RS into one column, count distinct names.",
        "SELECT COUNT(*) FROM (SELECT team_name_home AS name FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' UNION SELECT team_name_away AS name FROM game WHERE season_id = '22022' AND season_type = 'Regular Season');",
        ["game"],
        ["union", "subquery", "count"],
    ),
    (
        94,
        "extra_hard",
        "Rolling: no true rolling — instead list cumulative games played count is N/A; use window row_number over game_date for Celtics home 2022-23 RS, show first 5 game_dates ordered.",
        "SELECT game_date FROM (SELECT game_date, ROW_NUMBER() OVER (ORDER BY game_date) AS rn FROM game WHERE team_name_home = 'Boston Celtics' AND season_id = '22022' AND season_type = 'Regular Season') x WHERE rn <= 5 ORDER BY game_date;",
        ["game"],
        ["window", "subquery", "where", "order_by"],
    ),
    (
        95,
        "extra_hard",
        "Multi-condition: games where home won, scored 115+, and held opponent under 100 in 2022-23 RS, count.",
        "SELECT COUNT(*) FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND wl_home = 'W' AND pts_home >= 115 AND pts_away < 100;",
        ["game"],
        ["count", "where"],
    ),
    (
        96,
        "extra_hard",
        "draft_combine: max vertical leap among forwards (position contains F) in 2019 combine.",
        "SELECT MAX(max_vertical_leap) FROM draft_combine_stats WHERE season = '2019' AND position LIKE '%F%';",
        ["draft_combine_stats"],
        ["aggregate", "where"],
    ),
    (
        97,
        "extra_hard",
        "line_score: sum of all regulation quarter home points for one game_id from a high-scoring 2022-23 RS game — pick max total from line_score joined to game.",
        "SELECT ls.game_id, (ls.pts_qtr1_home + ls.pts_qtr2_home + ls.pts_qtr3_home + ls.pts_qtr4_home) AS reg_home_pts FROM line_score ls JOIN game g ON ls.game_id = g.game_id WHERE g.season_id = '22022' AND g.season_type = 'Regular Season' ORDER BY reg_home_pts DESC LIMIT 1;",
        ["line_score", "game"],
        ["join", "order_by", "limit"],
    ),
    (
        98,
        "extra_hard",
        "Percentile: team with median home pts in 2022-23 RS using OFFSET (approximate median team average).",
        "SELECT team_name_home FROM (SELECT team_name_home, AVG(pts_home) AS av, ROW_NUMBER() OVER (ORDER BY AVG(pts_home)) AS rn, COUNT(*) OVER () AS c FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' GROUP BY team_name_home) z WHERE rn = (c + 1) / 2;",
        ["game"],
        ["window", "subquery", "aggregate"],
    ),
    (
        99,
        "extra_hard",
        "Complex boolean: road wins for Lakers in 2022-23 RS when they were the away team.",
        "SELECT COUNT(*) FROM game WHERE season_id = '22022' AND season_type = 'Regular Season' AND team_name_away = 'Los Angeles Lakers' AND wl_away = 'W';",
        ["game"],
        ["count", "where"],
    ),
    (
        100,
        "extra_hard",
        "Self-join on game: count pairs of games on same game_date with same team_name_home (doubleheaders / data check) in 2022-23 RS.",
        "SELECT COUNT(*) FROM game a JOIN game b ON a.game_date = b.game_date AND a.team_name_home = b.team_name_home AND a.game_id < b.game_id WHERE a.season_id = '22022' AND a.season_type = 'Regular Season' AND b.season_id = '22022' AND b.season_type = 'Regular Season';",
        ["game"],
        ["join", "count", "where"],
    ),
]


def row_dict(t: tuple) -> dict:
    return {
        "id": t[0],
        "db_id": "nba",
        "question": t[2],
        "query": t[3],
        "difficulty": t[1],
        "tables_used": t[4],
        "sql_components": t[5],
    }


def main() -> None:
    if len(NEW) != 80:
        raise SystemExit(f"expected 80 new questions, got {len(NEW)}")
    conn = sqlite3.connect(DB)
    cur = conn.cursor()
    for t in NEW:
        sql = t[3]
        try:
            cur.execute(sql)
            cur.fetchall()
        except sqlite3.Error as e:
            raise SystemExit(f"SQL error id={t[0]}: {e}\n{sql}") from e
    conn.close()

    by_id = {x["id"]: x for x in EXISTING if x["id"] <= 20}
    for t in NEW:
        d = row_dict(t)
        if d["id"] in by_id:
            raise SystemExit(f"duplicate id {d['id']}")
        by_id[d["id"]] = d
    merged = [by_id[i] for i in range(1, 101)]
    OUT.write_text(json.dumps(merged, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("Wrote", OUT, "with", len(merged), "items; SQL ok for ids 21-100.")


if __name__ == "__main__":
    main()
